### ISSUE TITLE
Employee API End Points ideas

### ISSUE THREAD

**Issue by mathanamathav** [mathanamathav/Employee_Analytics_Platform#1]
@Tarun2704 Ideas for Employee Analytics

- [x] Average Vacation Time for each person yearly
- [ ] Different leave types bargraph
- [ ] Employee turnover rate
- [x] In hiring, What's the percentage of freshers and experienced
- [x] Age preference for recruitment

**Comment by mathanamathav** [comment]
@Tarun2704 @praneshKumarA we can try adding endpoints see the app.py file for reference

**Comment by praneshKumarA** [comment]
flask_sqlalchemy==3.0.3
mysqlclient==2.1.1
