### ISSUE TITLE
Department having duplicates

### ISSUE THREAD

**Issue by jegadeesh2001** [mathanamathav/Employee_Analytics_Platform#4]
Added Department wise Analysis and Demographic analysis in the back end file

**Comment by mathanamathav** [comment]
why issues, PR right?

**Comment by jegadeesh2001** [comment]
![image](https://user-images.githubusercontent.com/62760269/215255076-beb05e47-73dc-4680-9bed-008ac197cdff.png)

**Comment by mathanamathav** [comment]
we can fix this just delete one dept at the last

**Comment by jegadeesh2001** [comment]
![image](https://user-images.githubusercontent.com/62760269/215255118-92abe7eb-058a-4d4c-8b29-cc217cfed6e4.png)
As well as Approver id is incrementing. We should have designation as manager and only they can approve right

**Comment by jegadeesh2001** [comment]
> 

Yes training and legal should be changed

**Comment by mathanamathav** [comment]
@jegadeesh2001 fixed the dept issue -> dump https://drive.google.com/drive/u/2/folders/1tvaCl2A723MBiUxC3QHAAlU9oN-udogq
 
![image](https://user-images.githubusercontent.com/62739618/215255370-12b6d562-68cc-4c11-8d81-1313fdc1920e.png)

**Comment by mathanamathav** [comment]
> ![image](https://user-images.githubusercontent.com/62760269/215255118-92abe7eb-058a-4d4c-8b29-cc217cfed6e4.png) As well as Approver id is incrementing. We should have designation as manager and only they can approve right

yeah fixed that too
by keeping in the range between 25 - 250

![image](https://user-images.githubusercontent.com/62739618/215255585-b6d3bf73-324f-4443-b3b3-b5304c885fb8.png)

fixed and updated in drive

**Comment by mathanamathav** [comment]
@jegadeesh2001 both the issues are fixed reply if it's working for you too

**Comment by jegadeesh2001** [comment]
will check
